// <auto-generated />
namespace GraderDataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class BeforeFirstRelease : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BeforeFirstRelease));
        
        string IMigrationMetadata.Id
        {
            get { return "201501250807432_BeforeFirstRelease"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
